/*
 * LEDMTX_cfg.c
 *
 *  Created on: Aug 1, 2023
 *      Author: Nada Mamdouh
 */
#include "../../LIB/STD_TYPES.h"

#include "../../MCAL/GPIO/GPIO_int.h"

#include "LEDMTX_cfg.h"
/* Configuration table */
MGPIO_Config_t rows[NO_ROWS]={
		{.Port=GPIO_PORTA,.Pin=GPIO_PIN0,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTA,.Pin=GPIO_PIN1,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTA,.Pin=GPIO_PIN2,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTA,.Pin=GPIO_PIN3,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTA,.Pin=GPIO_PIN4,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTA,.Pin=GPIO_PIN5,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTA,.Pin=GPIO_PIN6,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTA,.Pin=GPIO_PIN7,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED}

};
MGPIO_Config_t cols[NO_COLS]={
		{.Port=GPIO_PORTB,.Pin=GPIO_PIN0,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTB,.Pin=GPIO_PIN1,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTB,.Pin=GPIO_PIN5,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTB,.Pin=GPIO_PIN6,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTB,.Pin=GPIO_PIN7,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTB,.Pin=GPIO_PIN8,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTB,.Pin=GPIO_PIN9,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED},
		{.Port=GPIO_PORTB,.Pin=GPIO_PIN10,.Mode=GPIO_MODE_OUTPUT,.OutputType=GPIO_OT_PUSHPULL,.OutputSpeed=GPIO_LOW_SPEED}
};




